Adds eza and bat with checks for dependencies on install

diff --git a/hooks/post-up b/hooks/post-up
--- a/hooks/post-up
+++ b/hooks/post-up
@@ -25,3 +25,47 @@ rename the file to \`zprofile':
 
 MSG
 fi
+
+# Function to check the operating system
+get_os() {
+  os_name=$(uname -s)
+  case "$os_name" in
+    Linux*)     echo "Linux";;
+    Darwin*)    echo "macOS";;
+    *)          echo "Unknown";;
+  esac
+}
+
+os=$(get_os)
+echo "Operating System: $os"
+
+# Check if the OS variable is set correctly
+if [[ -z "$os" ]]; then
+  echo "Failed to determine the operating system."
+  exit 1
+fi
+
+# Function to check if a command exists
+check_command() {
+  command_name=$1
+
+  if ! command -v $command_name &> /dev/null; then
+    if [[ "$os" == "macOS" ]]; then
+      echo "Warning: $command_name is not installed. Please install it with \`brew install $command_name\`" >&2
+    elif [[ "$os" == "Linux" ]]; then
+      echo "Warning: $command_name is not installed. Please install it with \`paru -S $command_name\` or \`yay -S $command_name\`" >&2
+    else
+      echo "Warning: $command_name is not installed. Please install it" >&2
+    fi
+  fi
+}
+
+# List of required commands
+required_commands=("bat" "eza")
+
+# Check each required command
+echo "Checking for dependencies that need installing..."
+
+for cmd in $required_commands; do
+  check_command $cmd
+done
